import type { Metadata } from "next"
import Link from "next/link"
import Image from "next/image"
import { Button } from "@/components/ui/button"
import { ArrowLeft } from "lucide-react"

export const metadata: Metadata = {
  title: "Terms of Service | ExportRemix",
  description:
    "Terms of Service for ExportRemix - AI-powered logistics and supply chain management platform. User agreements, IP rights, disclaimers, and liability limits.",
}

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen gradient-flow">
      <nav className="border-b border-border/50 bg-background/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="container mx-auto px-4 py-3 sm:py-4">
          <div className="flex items-center justify-between">
            <Link href="/" className="flex items-center gap-2 sm:gap-3">
              <Image
                src="/logo.png"
                alt="ExportRemix Logo"
                width={32}
                height={32}
                className="h-6 w-6 sm:h-7 sm:w-7 md:h-9 md:w-9"
              />
              <span className="text-lg sm:text-xl md:text-2xl font-bold text-foreground">ExportRemix</span>
            </Link>
            <Link href="/">
              <Button variant="ghost" size="sm" className="gap-2">
                <ArrowLeft className="w-4 h-4" />
                <span className="hidden sm:inline">Back to Home</span>
                <span className="sm:hidden">Back</span>
              </Button>
            </Link>
          </div>
        </div>
      </nav>

      <div className="container mx-auto px-4 py-8 md:py-12 max-w-4xl">
        <div className="bg-card border border-border rounded-lg p-6 md:p-8 space-y-8">
          <div className="space-y-4">
            <h1 className="text-3xl md:text-4xl font-bold">Terms of Service</h1>
            <p className="text-sm text-muted-foreground">Last Updated: January 2025</p>
            <p className="text-base text-muted-foreground leading-relaxed">
              Welcome to ExportRemix. By accessing or using our platform, you agree to be bound by these Terms of
              Service. Please read them carefully.
            </p>
          </div>

          {/* 1. Agreement to Terms */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold">1. Agreement to Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              By creating an account, accessing, or using ExportRemix (the "Service"), you agree to comply with and be
              bound by these Terms of Service ("Terms"). If you do not agree to these Terms, you may not use the
              Service.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              These Terms constitute a legally binding agreement between you ("User," "you," or "your") and ExportRemix
              ("we," "us," or "our").
            </p>
          </section>

          {/* 2. Description of Services */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold">2. Description of Services</h2>
            <p className="text-muted-foreground leading-relaxed">
              ExportRemix provides AI-powered tools for logistics and supply chain management, including but not limited
              to:
            </p>
            <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4">
              <li>Predictive analytics for tariff surges and trade policy changes</li>
              <li>Smart manifest fixing and optimization using AI agents</li>
              <li>Policy monitoring and compliance alerts</li>
              <li>Data harmonization and export management tools</li>
            </ul>
            <div className="bg-primary/5 border border-primary/20 rounded-lg p-4 mt-4">
              <p className="text-sm font-semibold text-foreground mb-2">Important Disclaimer:</p>
              <p className="text-sm text-muted-foreground leading-relaxed">
                The Service provides <strong>estimates and predictions only</strong> and is{" "}
                <strong>not legal, financial, or professional advice</strong>. All predictions, recommendations, and
                analyses are generated by AI algorithms and should be independently verified. ExportRemix does not
                guarantee the accuracy, completeness, or reliability of any information provided.
              </p>
            </div>
          </section>

          {/* 3. User Accounts and Responsibilities */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold">3. User Accounts and Responsibilities</h2>
            <p className="text-muted-foreground leading-relaxed">
              To access certain features of the Service, you must create an account. You agree to:
            </p>
            <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4">
              <li>Provide accurate, current, and complete information during registration</li>
              <li>Maintain the security of your account credentials</li>
              <li>Notify us immediately of any unauthorized access or security breach</li>
              <li>Accept responsibility for all activities that occur under your account</li>
              <li>Use the Service only for lawful purposes and in compliance with all applicable laws</li>
            </ul>
          </section>

          {/* 4. Intellectual Property Rights */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold">4. Intellectual Property Rights</h2>
            <p className="text-muted-foreground leading-relaxed">
              All content, features, functionality, software, code, designs, graphics, logos, and trademarks on the
              Service are the exclusive property of ExportRemix and are protected by international copyright, trademark,
              and other intellectual property laws.
            </p>
            <p className="text-muted-foreground leading-relaxed">You agree not to:</p>
            <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4">
              <li>Copy, modify, distribute, or reproduce any part of the Service without written permission</li>
              <li>Reverse engineer, decompile, or disassemble any software or algorithms</li>
              <li>Remove or alter any copyright, trademark, or proprietary notices</li>
              <li>Use the Service to create competing products or services</li>
            </ul>
          </section>

          {/* 5. Limitation of Liability */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold">5. Limitation of Liability</h2>
            <p className="text-muted-foreground leading-relaxed">
              To the maximum extent permitted by law, ExportRemix and its affiliates, officers, employees, and agents
              shall not be liable for:
            </p>
            <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4">
              <li>
                Any indirect, incidental, special, consequential, or punitive damages arising from your use of the
                Service
              </li>
              <li>
                Any losses resulting from inaccurate predictions, estimates, or recommendations provided by the Service
              </li>
              <li>Business interruptions, lost profits, or data loss</li>
              <li>Errors, omissions, or delays in the Service</li>
            </ul>
            <div className="bg-muted/50 border border-border rounded-lg p-4 mt-4">
              <p className="text-sm font-semibold text-foreground mb-2">Maximum Liability:</p>
              <p className="text-sm text-muted-foreground leading-relaxed">
                Our total liability to you for any claims arising from or related to the Service is limited to the
                amount of fees you paid to ExportRemix in the twelve (12) months preceding the claim, or $100 USD,
                whichever is greater.
              </p>
            </div>
          </section>

          {/* 6. No Guarantees on Accuracy */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold">6. No Guarantees on Accuracy</h2>
            <p className="text-muted-foreground leading-relaxed">
              While we strive to provide accurate and reliable information, ExportRemix makes{" "}
              <strong>no warranties or guarantees</strong> regarding:
            </p>
            <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4">
              <li>The accuracy, completeness, or timeliness of predictions, alerts, or recommendations</li>
              <li>The suitability of the Service for your specific business needs</li>
              <li>Uninterrupted or error-free operation of the Service</li>
              <li>The prevention of all supply chain disruptions or tariff surges</li>
            </ul>
            <p className="text-muted-foreground leading-relaxed">
              The Service is provided "AS IS" and "AS AVAILABLE" without warranties of any kind, either express or
              implied.
            </p>
          </section>

          {/* 7. Data Privacy and Security */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold">7. Data Privacy and Security</h2>
            <p className="text-muted-foreground leading-relaxed">
              Your privacy is important to us. Our collection, use, and protection of your personal data is governed by
              our{" "}
              <Link href="/privacy" className="text-primary hover:underline">
                Privacy Policy
              </Link>
              , which is incorporated into these Terms by reference.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              By using the Service, you consent to the collection and use of your data as described in the Privacy
              Policy, including compliance with GDPR, CCPA, and other applicable data protection regulations.
            </p>
          </section>

          {/* 8. Subscription and Payment Terms */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold">8. Subscription and Payment Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              ExportRemix offers various subscription tiers (Free, Pro, Enterprise). By subscribing to a paid plan, you
              agree to:
            </p>
            <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4">
              <li>Pay all fees associated with your selected plan</li>
              <li>Provide accurate billing information</li>
              <li>Authorize automatic recurring charges unless you cancel your subscription</li>
            </ul>
            <p className="text-muted-foreground leading-relaxed">
              Fees are non-refundable except as required by law. You may cancel your subscription at any time, and
              cancellation will take effect at the end of your current billing period.
            </p>
          </section>

          {/* 9. Termination */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold">9. Termination</h2>
            <p className="text-muted-foreground leading-relaxed">
              We reserve the right to suspend or terminate your access to the Service at any time, with or without
              notice, for any reason, including but not limited to:
            </p>
            <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4">
              <li>Violation of these Terms</li>
              <li>Fraudulent, abusive, or illegal activity</li>
              <li>Non-payment of fees</li>
              <li>Prolonged inactivity</li>
            </ul>
            <p className="text-muted-foreground leading-relaxed">
              Upon termination, your right to use the Service will immediately cease, and we may delete your account and
              data.
            </p>
          </section>

          {/* 10. Modifications to Terms */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold">10. Modifications to Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              We reserve the right to modify these Terms at any time. We will notify you of material changes by posting
              the updated Terms on the Service or by email. Your continued use of the Service after such modifications
              constitutes your acceptance of the updated Terms.
            </p>
          </section>

          {/* 11. Governing Law and Dispute Resolution */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold">11. Governing Law and Dispute Resolution</h2>
            <p className="text-muted-foreground leading-relaxed">
              These Terms are governed by and construed in accordance with the laws of the United States, without regard
              to conflict of law principles. Any disputes arising from these Terms or the Service shall be resolved
              through binding arbitration in accordance with the rules of the American Arbitration Association.
            </p>
          </section>

          {/* 12. Contact Information */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold">12. Contact Information</h2>
            <p className="text-muted-foreground leading-relaxed">
              If you have any questions about these Terms of Service, please contact us:
            </p>
            <div className="bg-muted/50 border border-border rounded-lg p-4">
              <p className="text-sm text-muted-foreground">
                <strong>Email:</strong>{" "}
                <a href="mailto:support@exportremix.com" className="text-primary hover:underline">
                  support@exportremix.com
                </a>
              </p>
              <p className="text-sm text-muted-foreground mt-2">
                <strong>Support:</strong>{" "}
                <Link href="/support" className="text-primary hover:underline">
                  Visit our Support Center
                </Link>
              </p>
            </div>
          </section>

          {/* Acknowledgment */}
          <div className="bg-primary/5 border border-primary/20 rounded-lg p-6 mt-8">
            <p className="text-sm font-semibold text-foreground mb-3">Acknowledgment</p>
            <p className="text-sm text-muted-foreground leading-relaxed">
              By using ExportRemix, you acknowledge that you have read, understood, and agree to be bound by these Terms
              of Service. If you do not agree, please discontinue use of the Service immediately.
            </p>
          </div>
        </div>

        {/* CTA Section */}
        <div className="mt-8 text-center">
          <p className="text-muted-foreground mb-4">Ready to get started?</p>
          <Link href="/signup">
            <Button size="lg" className="gap-2">
              Create Free Account
            </Button>
          </Link>
        </div>
      </div>
    </div>
  )
}
